### ISSUE TITLE
Beta: Formatting/parsing issues in comments

### ISSUE THREAD

**Issue by Bwansen** [mutle/fu2#13]
When you nest a list into a blockquote, the list bullets overlay the vertical blockquote  marker line. (The bullets of the "All users" list show a similar behaviour.)
New lines after blockquotes are not correctly parsed, instead of a &lt;p&gt; for a double newline I get a simple &lt;br&gt;.
The numbers of numbered lists disappear behind the left margin.

**Comment by mutle** [comment]
Same as #42, so closing this one.
